#!/bin/bash
# Create all Ollama models from Modelfiles
# Generated by .ai/generate.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for modelfile in "$SCRIPT_DIR"/Modelfile.*; do
    if [[ -f "$modelfile" ]]; then
        name=$(basename "$modelfile" | sed 's/Modelfile\.//')
        echo "Creating model: oustip-$name"
        ollama create "oustip-$name" -f "$modelfile"
    fi
done

echo "All models created!"
